#!/usr/sh
#
# automate some tedious shit number 2
#
dirName=`echo $@ | tr ' ' '_' | tr '/' '-'`
mkdir $dirName
cd $dirName
#touch Custom\ Styles\ and\ Script\ for\ This\ Form.html
touch Hero.html
#touch Replacement\ Disclaimer.html
#~/bin/idea Replacement\ Disclaimer.html
~/bin/idea Hero.html
#~/bin/idea Custom\ Styles\ and\ Script\ for\ This\ Form.html
