#!/bin/zsh
#
# automate some tedious shit number 2
#
dirName=`echo $@ | tr " " "_" | tr "/" "-" | tr -d ":"`
mkdir $dirName
cd $dirName
touch HTML.html
touch Plain\ Text.txt
~/bin/idea Plain\ Text.txt
~/bin/idea HTML.html
