#!/usr/bin/ruby
require 'fileutils'

if File.exist?(ARGV[0])
	in_file  = File.open(ARGV[0], 'r')
	out_file = File.open('/tmp/fix.tmp', 'w')
else
	puts "File #{ARGV[0]} not found."
	exit(1)
end

#noinspection RubyExpressionInStringInspection
trans_map = {
	"'s "                                   => '&rsquo;s ',
	"n't "                                  => 'n&rsquo;t ',
	'’'                                     => '&rsquo;',
	'\\\\' + "'"                            => '&rsquo;',
	'“'                                     => '&ldquo;',
	'”'                                     => '&rdquo;',
	'—'                                     => '&mdash;',
	' -- '                                  => ' &mdash; ',
	' –– '                                  => ' &mdash; ',
	' – '                                   => ' &mdash; ',
	'(?<first>[^!]{1})--(?<second>[^>]{1})' => '\k<first>&mdash;\k<second>',
	' - '                                   => ' &mdash; ',
	'  '                                    => ' ',
	' & '                                   => ' &amp; ',
	'…'                                     => '&hellip;',
	' '                                 => ' ',
	'®'                                     => '&reg;',
	'©'                                     => '&copy;',
	' "(?<quoted>[\s\w]+)" 	'               => ' &ldquo;\k<quoted>&rdquo; ',
	'\.\.\.'                                => '&hellip;'
}

in_file.each do |line|

	trans_map.each do |key, value|
		line = line.gsub /#{key}/, value
	end # end loop throuh replacements
	out_file.write line
end # end loop through file

in_file.close
out_file.close
FileUtils.mv '/tmp/fix.tmp', ARGV[0]
