#!/bin/sh
# generate sha512 integrity HTML attribute
openssl dgst -sha384 -binary "$1" | openssl base64 -A -out "$1".sha384
sed -i.old '1s;^;integrity="sha384-;' "$1".sha384
echo "\" crossorigin=\"anonymous\"" >> "$1".sha384
