#!/bin/sh
# generate sha512 integrity HTML attribute
openssl dgst -sha512 -binary "$1" | openssl base64 -A -out "$1".sha512
printf "%s%s%s" ' integrity="sha512-' "$(cat $1.sha512)" "\" crossorigin=\"anonymous\" " > "$1".integrity
