#! /usr/bin/perl
#
# removes empty directories
# syntax rmEmpty [directory]

use strict;
use warnings;
use File::Find;
use English;

my $targetDir = '.';

if ($ARGV[0]) {
	$targetDir = $ARGV[0];
}

finddepth(sub{rmdir},$targetDir)